<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
  </head>
  <body>
    <p>This is my chained promise for coffee </p>

    <script>
        //chained promise 
       /* fetch('coffee.jpg')
        .then(response => {
            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            } else {
                return response.blob();
            }
        })
        .then(myBlob => {
            let objectURL = URL.createObjectURL(myBlob);
            let image = document.createElement('img');
            image.src = objectURL;
            document.body.appendChild(image);
        })
        .catch(e => {
            console.log('There has been a problem with your fetch operation: ' + e.message);
        }).finally( ()=> {
            console.log("fetch ended, either good or bad");
        });*/

        async function myFetch() {
            let response = await fetch('coffee.jpg');

            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }

            let myBlob = await response.blob();

                let objectURL = URL.createObjectURL(myBlob);
                let image = document.createElement('img');
                image.src = objectURL;
                document.body.appendChild(image);
            }

            myFetch()
            .catch(e => {
            console.log('There has been a problem with your fetch operation: ' + e.message);
    }).finally( ()=> {
            console.log("async fetch ended, either good or bad");
        });
    


    </script>
  </body>
</html>